raster_plot:
  _target_: lfads_torch.callbacks.RasterPlot
  log_every_n_epochs: 500

trajectory_plot:
  _target_: lfads_torch.callbacks.TrajectoryPlot
  log_every_n_epochs: 500

evaluation_callback:
  _target_: lfads_torch.extensions.nlb.NLBEvaluation
  log_every_n_epochs: 5
